"""empty message

Revision ID: a4af75ec55b0
Revises: 
Create Date: 2026-04-04 00:03:26.194487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4af75ec55b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_sessions', schema=None) as batch_op:
        batch_op.alter_column('unit_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_sessions', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('unit_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
